In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import tensorflow as tf

Initialzation

In [5]:
x= tf.constant(4, shape=(1,1), dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [7]:
x=tf.constant([[1,2,3],[4,5,6]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [8]:
x=tf.ones((3,3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [9]:
x=tf.zeros((2,3))
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [10]:
x=tf.eye(3)
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [11]:
x=tf.random.normal((3,3), mean=0, stddev=1)
print(x)

tf.Tensor(
[[ 1.2554982  -0.4372387   0.23801333]
 [-0.67376745  0.3031395  -0.81905204]
 [ 0.9141159  -0.5978334   2.2489839 ]], shape=(3, 3), dtype=float32)


In [12]:
x=tf.random.uniform((1,3), minval=0, maxval=1)
print(x)

tf.Tensor([[0.17942417 0.49162853 0.76814425]], shape=(1, 3), dtype=float32)


In [13]:
x= tf.range(9)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [14]:
x=tf.range(start=1, limit=10, delta=2)
print(x)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [20]:
x=tf.cast(x, dtype=tf.float16)
print(x)
#tf.float(16,32,64) #tf.int(8,16,32,64) #tf.bool

tf.Tensor([ True  True  True  True  True], shape=(5,), dtype=bool)


Mathematical Operations

In [21]:
x=tf.constant([1,2,3])
y=tf.constant([9,8,7])

In [25]:
z=tf.add(x,y)
print(z)
#z=x+y

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [27]:
z=tf.subtract(x,y)
print(z)
#z=x-y

tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)


In [28]:
z=tf.multiply(x,y)
print(z)
#z=x*y

tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)


In [29]:
z=tf.divide(x,y)
print(z)
#z=x/y

tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)


In [30]:
z=tf.tensordot(x,y, axes=1)
print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [31]:
z=tf.reduce_sum(x*y, axis=0)
print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [32]:
z=x**5
print(z)

tf.Tensor([  1  32 243], shape=(3,), dtype=int32)


In [34]:
x= tf.random.normal((2,3))
y= tf.random.normal((3,4))
z=tf.matmul(x,y)
print(z)
z=x@y
print(z)

tf.Tensor(
[[ 5.4436      0.07059371  4.894543   -1.180138  ]
 [ 0.23002446 -0.13115203  0.8976177   0.24881233]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[ 5.4436      0.07059371  4.894543   -1.180138  ]
 [ 0.23002446 -0.13115203  0.8976177   0.24881233]], shape=(2, 4), dtype=float32)


Indexing

In [36]:
x= tf.constant([0,1,1,2,3,1,2,3])
print(x[:])
print(x[1:])
print(x[1:3])
print(x[::2])
print(x[::-1])
indices=tf.constant([0,3])
x_ind=tf.gather(x,indices)
print(x_ind)

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)
tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)
tf.Tensor([0 2], shape=(2,), dtype=int32)


In [37]:
x=tf.constant([[1,2],[3,4],[5,6]])
print(x[0,:])
print(x[0:2,:])

tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


Reshaping

In [46]:
x=tf.range(9)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [47]:
x =tf.reshape(x,(3,3))
print(x)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [48]:
x=tf.transpose(x, perm=[1,0])
print(x)

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
